name: Core

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Core System Info
        run: |
          tox -e py

      - name: Integration Tests
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          tox -e testcore

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Core*'
          commit: true
          url: ${{ secrets.SLACK_BUILD_WEBHOOK }}
          token: ${{ secrets.SLACK_GITHUB_TOKEN }}
